### ISSUE TITLE
Server Errors

### ISSUE THREAD

**Issue by slavakurilyak** [stackbit/sourcebit-target-next#6]
I am running Stackbit v0.3.44, using Next.js as a web framework and Contentful as a CMS.

I am trying to create two new Contentful Content Models: `Live` and `Event`.

`Live` is a duplicate model to `Blog` while `Event` is a duplicate model to `Post`.

After having defined Content Models and Content Entries in Contentful, I deployed to Github.

StackBit Studio shows me Server Errors for both `/live` and `/live/new-event` URLs. See two screenshots below.

![screen-1](https://user-images.githubusercontent.com/6625584/106096267-0fe1c480-60ea-11eb-96a0-102b36fa78ff.jpg)

![screen-2](https://user-images.githubusercontent.com/6625584/106096272-12dcb500-60ea-11eb-9a20-4f2106bcf65b.jpg)

Stackbit Developer Logs shows me:

```
9:45:25 PM: [nextjs]: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
9:45:25 PM: [nextjs]: at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:4006:17)
9:45:25 PM: [nextjs]: at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
9:45:25 PM: [nextjs]: at renderToString (node_modules/react-dom/cjs/react-dom-server.node.development.js:4245:27)
9:45:25 PM: [nextjs]: at Object.renderPage (node_modules/next/dist/next-server/server/render.js:48:686)
9:45:25 PM: [nextjs]: at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:129:19)
9:45:25 PM: [nextjs]: at Function.getInitialProps (webpack-internal:///./src/pages/_document.js:30:85)
9:45:25 PM: [nextjs]: at loadGetInitialProps (node_modules/next/dist/next-server/lib/utils.js:5:101)
9:45:25 PM: [nextjs]: at renderToHTML (node_modules/next/dist/next-server/server/render.js:48:977)
9:45:29 PM: [nextjs]: Page [...slug].js getStaticPaths
9:45:29 PM: [nextjs]: SourcebitDataClient.getStaticPaths
9:45:29 PM: [nextjs]: SourcebitDataClient.getData
9:45:29 PM: [nextjs]: Page [...slug].js getStaticProps, params:
9:45:29 PM: [nextjs]: SourcebitDataClient.getStaticPropsForPath
9:45:29 PM: [nextjs]: SourcebitDataClient.getData
9:45:29 PM: [nextjs]: Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
9:45:29 PM: [nextjs]: Check your code at [...slug].js:15.
9:45:29 PM: [nextjs]: in Page
9:45:29 PM: [nextjs]: in WithRemoteDataUpdates(Page)
9:45:29 PM: [nextjs]: in withRouter(WithRemoteDataUpdates(Page)) (at _app.js:38)
9:45:29 PM: [nextjs]: in MyApp
9:45:29 PM: [nextjs]: in Unknown
9:45:29 PM: [nextjs]: in Context.Provider
9:45:29 PM: [nextjs]: in Context.Provider
9:45:29 PM: [nextjs]: in Context.Provider
9:45:29 PM: [nextjs]: in Context.Provider
9:45:29 PM: [nextjs]: in AppContainer
```

Netlify Deployment logs shows me:

```
9:27:27 PM: Build ready to start
9:27:28 PM: build-image version: d84c79427e8f83c1ba17bcdd7b3fe38059376b68
9:27:28 PM: build-image tag: v3.6.1
9:27:28 PM: buildbot version: 44655717ddf0e7bd7f856f5b1154254de54b1d80
9:27:29 PM: Fetching cached dependencies
9:27:29 PM: Starting to download cache of 99.8MB
9:27:29 PM: Finished downloading cache in 679.179914ms
9:27:29 PM: Starting to extract cache
9:27:32 PM: Finished extracting cache in 3.161963265s
9:27:32 PM: Finished fetching cache in 3.872718975s
9:27:32 PM: Starting to prepare the repo for build
9:27:33 PM: Preparing Git Reference refs/heads/master
9:27:35 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'out' versus '/' in the Netlify UI
9:27:35 PM: Different build command detected, going to use the one specified in the Netlify configuration file: './stackbit-build.sh' versus '' in the Netlify UI
9:27:35 PM: Starting build script
9:27:35 PM: Installing dependencies
9:27:35 PM: Python version set to 2.7
9:27:35 PM: Started restoring cached node version
9:27:38 PM: Finished restoring cached node version
9:27:38 PM: v12.18.0 is already installed.
9:27:39 PM: Now using node v12.18.0 (npm v6.14.4)
9:27:39 PM: Started restoring cached build plugins
9:27:39 PM: Finished restoring cached build plugins
9:27:39 PM: Attempting ruby version 2.7.1, read from environment
9:27:40 PM: Using ruby version 2.7.1
9:27:40 PM: Using PHP version 5.6
9:27:40 PM: Started restoring cached node modules
9:27:40 PM: Finished restoring cached node modules
9:27:41 PM: Started restoring cached go cache
9:27:41 PM: Finished restoring cached go cache
9:27:41 PM: go version go1.14.4 linux/amd64
9:27:41 PM: go version go1.14.4 linux/amd64
9:27:41 PM: Installing missing commands
9:27:41 PM: Verify run directory
9:27:42 PM: ​
9:27:42 PM: ────────────────────────────────────────────────────────────────
9:27:42 PM:   Netlify Build                                                 
9:27:42 PM: ────────────────────────────────────────────────────────────────
9:27:42 PM: ​
9:27:42 PM: ❯ Version
9:27:42 PM:   @netlify/build 8.3.0
9:27:42 PM: ​
9:27:42 PM: ❯ Flags
9:27:42 PM:   deployId: 60124b3febf8ff5cd8cb2198
9:27:42 PM:   mode: buildbot
9:27:42 PM: ​
9:27:42 PM: ❯ Current directory
9:27:42 PM:   /opt/build/repo
9:27:42 PM: ​
9:27:42 PM: ❯ Config file
9:27:42 PM:   /opt/build/repo/netlify.toml
9:27:42 PM: ​
9:27:42 PM: ❯ Context
9:27:42 PM:   production
9:27:42 PM: ​
9:27:42 PM: ────────────────────────────────────────────────────────────────
9:27:42 PM:   1. build.command from netlify.toml                            
9:27:42 PM: ────────────────────────────────────────────────────────────────
9:27:42 PM: ​
9:27:42 PM: $ ./stackbit-build.sh
9:27:42 PM: echo "stackbit-build.sh: start build"
9:27:42 PM: stackbit-build.sh: start build
9:27:42 PM: # build site
9:27:42 PM: npm run build
9:27:43 PM: > azimuth@0.0.1 build /opt/build/repo
9:27:43 PM: > next build && next export
9:27:43 PM: Browserslist: caniuse-lite is outdated. Please run:
9:27:43 PM: npx browserslist@latest --update-db
9:27:44 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
9:27:44 PM: info  - Creating an optimized production build...
9:27:44 PM: Browserslist: caniuse-lite is outdated. Please run:
9:27:44 PM: npx browserslist@latest --update-db
9:28:09 PM: info  - Compiled successfully
9:28:09 PM: info  - Collecting page data...
9:28:10 PM: Page [...slug].js getStaticPaths
9:28:10 PM: SourcebitDataClient.getStaticPaths
9:28:10 PM: SourcebitDataClient.getData
9:28:10 PM: info  - Generating static pages (0/22)
9:28:11 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'contact' ] }
9:28:11 PM: SourcebitDataClient.getStaticPropsForPath
9:28:11 PM: SourcebitDataClient.getData
9:28:11 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'live' ] }
9:28:11 PM: SourcebitDataClient.getStaticPropsForPath
9:28:11 PM: SourcebitDataClient.getData
9:28:11 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'pricing' ] }
9:28:11 PM: SourcebitDataClient.getStaticPropsForPath
9:28:11 PM: SourcebitDataClient.getData
9:28:11 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'blog' ] }
9:28:11 PM: SourcebitDataClient.getStaticPropsForPath
9:28:11 PM: SourcebitDataClient.getData
9:28:11 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'features' ] }
9:28:11 PM: SourcebitDataClient.getStaticPropsForPath
9:28:11 PM: SourcebitDataClient.getData
9:28:12 PM: Error occurred prerendering page "/live". Read more: https://err.sh/next.js/prerender-error
9:28:12 PM: Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
9:28:12 PM:     at a.b.render (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:48:37)
9:28:12 PM:     at a.b.read (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
9:28:12 PM:     at renderToString (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
9:28:12 PM:     at Object.renderPage (/opt/build/repo/node_modules/next/dist/next-server/server/render.js:48:686)
9:28:12 PM:     at Function.getInitialProps (/opt/build/repo/.next/server/pages/_document.js:924:19)
9:28:12 PM:     at Function.getInitialProps (/opt/build/repo/.next/server/pages/_document.js:3046:85)
9:28:12 PM:     at loadGetInitialProps (/opt/build/repo/node_modules/next/dist/next-server/lib/utils.js:5:101)
9:28:12 PM:     at renderToHTML (/opt/build/repo/node_modules/next/dist/next-server/server/render.js:48:977)
9:28:12 PM:     at async Object.exportPage [as default] (/opt/build/repo/node_modules/next/dist/export/worker.js:25:6)
9:28:12 PM: info  - Generating static pages (1/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'signup' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'about' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (2/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'terms-of-service' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (3/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'style-guide' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: Page [index] getStaticProps, params:  undefined
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (4/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'privacy-policy' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (5/22)
9:28:12 PM: info  - Generating static pages (6/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'blog', 'design-team-collaborates' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'blog', 'design-azimuth' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (7/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'blog', 'working-from-home' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (8/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'blog', 'user-journey-mapping' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (9/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'blog', 'set-big-goals' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (10/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'blog', 'sales-as-service' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (11/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'blog', 'customer-loyalty' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (12/22)
9:28:12 PM: info  - Generating static pages (13/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  {
9:28:12 PM:   slug: [ 'blog', 'customer-service-skills-that-every-employee-needs' ]
9:28:12 PM: }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'blog', 'azimuth-improvements' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (14/22)
9:28:12 PM: Page [...slug].js getStaticProps, params:  { slug: [ 'live', 'how-to-source-or-find-global-talent' ] }
9:28:12 PM: SourcebitDataClient.getStaticPropsForPath
9:28:12 PM: SourcebitDataClient.getData
9:28:12 PM: info  - Generating static pages (15/22)
9:28:12 PM: info  - Generating static pages (16/22)
9:28:12 PM: Error occurred prerendering page "/live/how-to-source-or-find-global-talent". Read more: https://err.sh/next.js/prerender-error
9:28:12 PM: Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
9:28:12 PM:     at a.b.render (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:48:37)
9:28:12 PM:     at a.b.read (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
9:28:12 PM:     at renderToString (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
9:28:12 PM:     at Object.renderPage (/opt/build/repo/node_modules/next/dist/next-server/server/render.js:48:686)
9:28:12 PM:     at Function.getInitialProps (/opt/build/repo/.next/server/pages/_document.js:924:19)
9:28:12 PM:     at Function.getInitialProps (/opt/build/repo/.next/server/pages/_document.js:3046:85)
9:28:12 PM:     at loadGetInitialProps (/opt/build/repo/node_modules/next/dist/next-server/lib/utils.js:5:101)
9:28:12 PM:     at renderToHTML (/opt/build/repo/node_modules/next/dist/next-server/server/render.js:48:977)
9:28:12 PM:     at async Object.exportPage [as default] (/opt/build/repo/node_modules/next/dist/export/worker.js:25:6)
9:28:12 PM: info  - Generating static pages (17/22)
9:28:12 PM: info  - Generating static pages (18/22)
9:28:12 PM: info  - Generating static pages (19/22)
9:28:12 PM: info  - Generating static pages (20/22)
9:28:12 PM: info  - Generating static pages (21/22)
9:28:12 PM: info  - Generating static pages (22/22)
9:28:12 PM: > Build error occurred
9:28:12 PM: Error: Export encountered errors on following paths:
9:28:12 PM: 	/live
9:28:12 PM: 	/live/how-to-source-or-find-global-talent
9:28:12 PM:     at exportApp (/opt/build/repo/node_modules/next/dist/export/index.js:24:1103)
9:28:12 PM:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
9:28:12 PM:     at async build (/opt/build/repo/node_modules/next/dist/build/index.js:37:212)
9:28:12 PM: npm ERR! code ELIFECYCLE
9:28:12 PM: npm ERR! errno 1
9:28:12 PM: npm ERR! azimuth@0.0.1 build: `next build && next export`
9:28:12 PM: npm ERR! Exit status 1
9:28:12 PM: npm ERR!
9:28:12 PM: npm ERR! Failed at the azimuth@0.0.1 build script.
9:28:12 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
9:28:12 PM: npm ERR! A complete log of this run can be found in:
9:28:12 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-01-28T05_28_12_733Z-debug.log
9:28:12 PM: ​
9:28:12 PM: ────────────────────────────────────────────────────────────────
9:28:12 PM:   "build.command" failed                                        
9:28:13 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
9:28:12 PM: ────────────────────────────────────────────────────────────────
9:28:12 PM: ​
9:28:12 PM:   Error message
9:28:12 PM:   Command failed with exit code 1: ./stackbit-build.sh
9:28:12 PM: ​
9:28:12 PM:   Error location
9:28:12 PM:   In build.command from netlify.toml:
9:28:12 PM:   ./stackbit-build.sh
9:28:12 PM: ​
9:28:12 PM:   Resolved config
9:28:12 PM:   build:
9:28:12 PM:     command: ./stackbit-build.sh
9:28:12 PM:     commandOrigin: config
9:28:12 PM:     environment:
9:28:12 PM:       - CONTENTFUL_ACCESS_TOKEN
9:28:12 PM:       - CONTENTFUL_DELIVERY_TOKEN
9:28:12 PM:       - INCOMING_HOOK_BODY
9:28:12 PM:       - INCOMING_HOOK_TITLE
9:28:12 PM:       - INCOMING_HOOK_URL
9:28:12 PM:     publish: /opt/build/repo/out
9:28:12 PM: Caching artifacts
9:28:12 PM: Started saving node modules
9:28:12 PM: Finished saving node modules
9:28:12 PM: Started saving build plugins
9:28:12 PM: Finished saving build plugins
9:28:12 PM: Started saving pip cache
9:28:12 PM: Finished saving pip cache
9:28:12 PM: Started saving emacs cask dependencies
9:28:13 PM: Finished saving emacs cask dependencies
9:28:13 PM: Started saving maven dependencies
9:28:13 PM: Finished saving maven dependencies
9:28:13 PM: Started saving boot dependencies
9:28:13 PM: Finished saving boot dependencies
9:28:13 PM: Started saving rust rustup cache
9:28:13 PM: Finished saving rust rustup cache
9:28:13 PM: Started saving go dependencies
9:28:13 PM: Finished saving go dependencies
9:28:13 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
9:28:13 PM: Failing build: Failed to build site
9:28:13 PM: Finished processing build request in 44.239051117s
```

The errors occur when I modify the `sourcebit.js` file to include `live` and `event`:

```
{
            module: require('sourcebit-target-next'),
            options: {
                liveUpdate: isDev,
                flattenAssetUrls: true,
                pages: [
                    { path: '/{stackbit_url_path}', predicate: _.matchesProperty('__metadata.modelName', 'landing') },
                    { path: '/{stackbit_url_path}', predicate: _.matchesProperty('__metadata.modelName', 'blog') },
                    { path: '/{stackbit_url_path}', predicate: _.matchesProperty('__metadata.modelName', 'live') },
                    { path: '/{stackbit_url_path}', predicate: _.matchesProperty('__metadata.modelName', 'page') },
                    { path: '/{stackbit_url_path}', predicate: _.matchesProperty('__metadata.modelName', 'post') },
                    { path: '/{stackbit_url_path}', predicate: _.matchesProperty('__metadata.modelName', 'event') }
                ],
                commonProps: (items) => {
                    return {
                        pages: _.filter(items, item => ["landing","blog","live","page","post","event"].includes(_.get(item, '__metadata.modelName'))),
                        data: {
                            config: _.find(items, _.matchesProperty('__metadata.modelName', 'config'))
                        }
                    };
                }
            }
        }
```

Thoughts?

**Comment by slavakurilyak** [comment]
I forgot to update `src/layouts/index.js` to include `live` and `event`
